# Generated by Django 5.2.14 on 2026-06-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LinkedInLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("linkedin_url", models.URLField(blank=True)),
                ("job_title", models.CharField(blank=True, max_length=200)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, default="Nigeria", max_length=100),
                ),
                (
                    "engagement_type",
                    models.CharField(
                        choices=[
                            ("comment", "Comment"),
                            ("like", "Like"),
                            ("share", "Share"),
                            ("poll_vote", "Poll Vote"),
                            ("profile_view", "Profile View"),
                            ("newsletter", "Newsletter Subscriber"),
                            ("dm", "Direct Message"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "post_url",
                    models.URLField(
                        blank=True, help_text="LinkedIn post that triggered this lead"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("replied", "Replied"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("dead", "Dead"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("dm_sent", models.BooleanField(default=False)),
                ("dm_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "LinkedIn Lead",
                "verbose_name_plural": "LinkedIn Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
