# Generated by Django 5.2.14 on 2026-05-19 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("business_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("barber", "Barber / Hair Stylist"),
                            ("plumber", "Plumber"),
                            ("electrician", "Electrician"),
                            ("carpenter", "Carpenter"),
                            ("painter", "Painter"),
                            ("cleaner", "Cleaner"),
                            ("mechanic", "Mechanic"),
                            ("tailor", "Tailor"),
                            ("tutor", "Tutor"),
                            ("gardener", "Gardener"),
                            ("photographer", "Photographer"),
                            ("caterer", "Caterer"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="provider_logos/"
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=300)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="Nigeria", max_length=100)),
                (
                    "whatsapp_number",
                    models.CharField(
                        help_text="Customers will be sent this number on WhatsApp",
                        max_length=20,
                    ),
                ),
                (
                    "facebook_page_url",
                    models.URLField(
                        blank=True,
                        help_text="Your Facebook page link shared with customers",
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
