# Generated by Django 5.2.14 on 2026-07-09 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['city', 'category'], name='services_se_city_f00834_idx'),
        ),
    ]
