# Generated by Django 5.2.14 on 2026-07-29 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def gen_promo_codes(apps, schema_editor):
    ServiceProvider = apps.get_model('services', 'ServiceProvider')
    import uuid
    for provider in ServiceProvider.objects.all():
        if not provider.promo_code:
            business_prefix = "".join(filter(str.isalnum, provider.business_name)).upper()[:4]
            random_suffix = str(uuid.uuid4())[:4].upper()
            provider.promo_code = f"PROMO-{business_prefix}-{random_suffix}"
            provider.save()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add promo_code as non-unique, nullable field temporarily
        migrations.AddField(
            model_name='serviceprovider',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # Step 2: Run Python script to generate unique promo codes for existing rows
        migrations.RunPython(gen_promo_codes),
        # Step 3: Alter field to make it unique and non-nullable
        migrations.AlterField(
            model_name='serviceprovider',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, unique=True, default=""),
            preserve_default=False,
        ),
        # Step 4: Create Referral model
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rewarded', models.BooleanField(default=False)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_info', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_records', to='services.serviceprovider')),
            ],
        ),
    ]
