# Generated by Django 5.2.14 on 2026-08-03 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_serviceprovider_promo_code_referral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['is_active'], name='services_se_is_acti_1abe67_idx'),
        ),
    ]
