# Generated by Django 5.2.14 on 2026-06-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supabase_uid',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
