# Generated by Django 5.2.14 on 2026-05-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20, unique=True)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank if same as phone. Must be in format +2348012345678",
                        max_length=20,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City where this person lives", max_length=100
                    ),
                ),
                ("opted_in_whatsapp", models.BooleanField(default=True)),
                ("opted_in_facebook", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["city", "name"],
            },
        ),
    ]
