# Generated by Django 5.2.14 on 2026-05-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20, unique=True)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank if same as phone. Must be in format +2348012345678",
                        max_length=20,
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City where this person lives / looks for services",
                        max_length=100,
                    ),
                ),
                (
                    "service_interest",
                    models.CharField(
                        choices=[
                            ("barber", "Barber / Hair Stylist"),
                            ("plumber", "Plumber"),
                            ("electrician", "Electrician"),
                            ("carpenter", "Carpenter"),
                            ("painter", "Painter"),
                            ("cleaner", "Cleaner"),
                            ("mechanic", "Mechanic"),
                            ("tailor", "Tailor"),
                            ("tutor", "Tutor"),
                            ("gardener", "Gardener"),
                            ("photographer", "Photographer"),
                            ("caterer", "Caterer"),
                            ("other", "Other"),
                        ],
                        help_text="What type of service this person is likely to need",
                        max_length=50,
                    ),
                ),
                (
                    "opted_in_whatsapp",
                    models.BooleanField(
                        default=True,
                        help_text="Can the platform send them WhatsApp messages?",
                    ),
                ),
                (
                    "opted_in_facebook",
                    models.BooleanField(
                        default=False,
                        help_text="Can the platform send them Facebook messages?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["city", "service_interest"],
            },
        ),
    ]
