# Generated by Django 5.2.14 on 2026-07-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['city', 'name'], name='customers_c_city_e62c03_idx'),
        ),
    ]
