# Generated by Django 5.2.14 on 2026-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_customers_c_city_e62c03_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active', 'opted_in_whatsapp'], name='customers_c_is_acti_43246c_idx'),
        ),
    ]
