# Generated by Django 5.2.14 on 2026-08-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceprovider_services_se_is_acti_1abe67_idx'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['is_active', 'status'], name='subscriptio_is_acti_07e03e_idx'),
        ),
    ]
